from fpdf import FPDF
from io import BytesIO

def export_screenplay(project_data):
    """Export screenplay as plain text"""
    screenplay_text = f"""
{project_data['title']}
Genre: {project_data['genre']}

{'='*60}

{project_data['screenplay']}

{'='*60}

Generated by Scriptoria - AI Film Pre-Production Studio
"""
    return screenplay_text

def export_full_project(project_data, format='pdf'):
    """Export complete project as PDF"""
    if format == 'pdf':
        return _export_pdf(project_data)
    return None

def _export_pdf(project_data):
    """Generate PDF export of full project"""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Title Page
    pdf.add_page()
    pdf.set_font('Arial', 'B', 24)
    pdf.cell(0, 20, project_data['title'], ln=True, align='C')
    
    pdf.set_font('Arial', 'I', 14)
    pdf.cell(0, 10, f"Genre: {project_data['genre']}", ln=True, align='C')
    pdf.ln(10)
    
    pdf.set_font('Arial', '', 12)
    pdf.multi_cell(0, 10, 'Generated by Scriptoria - AI Film Pre-Production Studio')
    
    # Screenplay Section
    pdf.add_page()
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, 'SCREENPLAY', ln=True)
    pdf.ln(5)
    
    pdf.set_font('Arial', '', 10)
    screenplay_lines = project_data['screenplay'].split('\n')
    for line in screenplay_lines[:100]:  # Limit for PDF size
        try:
            pdf.multi_cell(0, 5, line.encode('latin-1', 'replace').decode('latin-1'))
        except:
            pdf.multi_cell(0, 5, line.encode('ascii', 'ignore').decode('ascii'))
    
    # Characters Section
    pdf.add_page()
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, 'CHARACTER PROFILES', ln=True)
    pdf.ln(5)
    
    for char in project_data['characters']:
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 8, char['name'], ln=True)
        
        pdf.set_font('Arial', '', 10)
        pdf.multi_cell(0, 5, f"Background: {char['background'][:200]}")
        pdf.multi_cell(0, 5, f"Personality: {char['personality'][:200]}")
        pdf.multi_cell(0, 5, f"Motivation: {char['motivation'][:200]}")
        pdf.ln(5)
    
    # Sound Design Section
    pdf.add_page()
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, 'SOUND DESIGN', ln=True)
    pdf.ln(5)
    
    for sound in project_data['sound_design']:
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(0, 7, sound['scene'], ln=True)
        
        pdf.set_font('Arial', '', 10)
        pdf.multi_cell(0, 5, f"Music: {sound['music']}")
        pdf.multi_cell(0, 5, f"Ambient: {sound['ambient']}")
        pdf.ln(3)
    
    # Budget Section
    pdf.add_page()
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, 'PRODUCTION BUDGET', ln=True)
    pdf.ln(5)
    
    budget = project_data['budget']
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 8, f"Cast: ${budget['cast']:,}", ln=True)
    pdf.cell(0, 8, f"Crew: ${budget['crew']:,}", ln=True)
    pdf.cell(0, 8, f"Equipment: ${budget['equipment']:,}", ln=True)
    pdf.cell(0, 8, f"Locations: ${budget['locations']:,}", ln=True)
    pdf.cell(0, 8, f"Sound: ${budget['sound']:,}", ln=True)
    pdf.cell(0, 8, f"Post-Production: ${budget['post_production']:,}", ln=True)
    pdf.ln(5)
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f"TOTAL: ${budget['total']:,}", ln=True)
    
    # Output to bytes
    pdf_output = BytesIO()
    pdf_bytes = pdf.output(dest='S').encode('latin-1')
    return pdf_bytes
